### ISSUE TITLE
Save InvalidPSF to HDF5 format

### ISSUE THREAD

**Issue by colasri** [threeML/hawc_hal#16]
We can't convert detector response files of the energy estimators to HDF5 because they contain InvalidPSF instances.
One way to solve it would be to allow writing of the InvalidPSF class. Any opinion @giacomov ?

**Comment by giacomov** [comment]
Would you prefer writing InvalidPSF instances (an easy fix), or not writing in the file invalid bins?

I believe you already implemented the possibility of loading responses with missing bins, right?

**Comment by colasri** [comment]
I think there is a check somewhere that each declination has the same number of analysis bins (planes), so writing InvalidPSF would probably induce the minimum number of changes.
