### ISSUE TITLE
automated tests fail on osX due to issues with ROOT

### ISSUE THREAD

**Issue by henrikef** [threeML/hawc_hal#24]
A bunch of the travis CI tests fail on osX, ultimately due to problems with pyROOT/ROOT.

Tests work fine on linux now, as well as locally on my laptop. Any ideas? @grburgess @giacomov 

```
>   import libPyROOT as _root
E   ImportError: dlopen(/Users/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/libPyROOT.so, 2): Library not loaded: @rpath/libssl.1.0.0.dylib
E     Referenced from: /Users/travis/miniconda/envs/test-environment/lib/root/libNet.5.so
E     Reason: image not found
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/ROOT.py:103: ImportError
```

**Comment by giacomov** [comment]
Looks like a problem with openssl. Most probably the package has been updated recently. Can you try fixing the version of openssl in `meta.yml` for 3ML to 1.0?

**Comment by henrikef** [comment]
This doesn't seem to be an issue anymore.
