### ISSUE TITLE
Cannot manually specify ntransits

### ISSUE THREAD

**Issue by cbrisboi** [threeML/hawc_hal#32]
In liff, you could specify the transits to use for the maps during analysis. I just noticed while working on an unrelated task that we cannot do the same for hal.

This should be straightforward to implement, a good task for a graduate student wanting to learn. Otherwise, I'll get to it eventually

**Comment by maloneka** [comment]
@cbrisboi is anyone actively working on this? This would be nice to have as we work on validation of pass 5 with the Crab strip.

**Comment by henrikef** [comment]
@maloneka There is a branch that implements this functionality (see #43 ). Feel free to test that branch on the Crab strip etc! It still needs unit tests for the new functionality before it can be merged to the master, though.

**Comment by maloneka** [comment]
@cbrisboi status update? Does this pass the tests yet?
