### ISSUE TITLE
Drop python2 support for hawc_hal

### ISSUE THREAD

**Issue by henrikef** [threeML/hawc_hal#39]
Considering https://www.python.org/doc/sunset-python-2/ and https://pip.pypa.io/en/stable/development/release-process/ (`pip` will drop python2 support in January 2021), as well as the recent issues getting hawc_hal running in a python2 environment (see https://github.com/threeML/hawc_hal/pull/37 ), I propose to stop officially supporting python2 with hawc_hal. 

Please comment here with feedback/opinions.

**Comment by cbrisboi** [comment]
I agree with this proposal.  The install instructions we discussed the other day @henrikef appear to install at least a partially working environment, but I'm not sure how compatible hawc_hal is supposed to be with python3 yet. We can discuss more details later.

**Comment by henrikef** [comment]
With the switch to github actions, we are not testing on python 2.7 anymore.
