### ISSUE TITLE
Alternative to root_numpy?

### ISSUE THREAD

**Issue by henrikef** [threeML/hawc_hal#42]
`root_numpy` is no longer maintained. We should find an alternative package for loading root files (or switch to hdf5 entirely).

From https://github.com/scikit-hep/root_numpy:

> root_numpy has not been actively maintained in several years. This is mostly due to the emergence of new alternatives which are both faster and more flexible.
>
>  * `uproot` provides support for reading and writing ROOT files without the need for an installation of ROOT. [See here for details](https://github.com/scikit-hep/uproot3).
>  * ROOT now natively supports converting objects into numpy arrays using either [directly using TTree](https://root.cern/doc/master/pyroot002__TTreeAsMatrix_8py.html) or with the newer [RDataFrame](https://root.cern.ch/doc/master/df026__AsNumpyArrays_8py.html)

**Comment by henrikef** [comment]
Going to re-open this because it's still an issue. `hawc_hal` will soon be the only part of `threeML` requiring `root` - even the `fermitools` have now dropped `root` as a dependency. @xiaojieww , I really hope you guys investigate an alternative like [uproot](https://uproot.readthedocs.io/en/latest/).

**Comment by torresramiro350** [comment]
I am working on removing any ROOT dependencies and implementing `uproot` into HAL

**Comment by xiaojieww** [comment]
> 

Thanks! @torresramiro350

**Comment by torresramiro350** [comment]
I think this should be closed as #78 addresses this issue.

**Comment by xiaojieww** [comment]
> 

Yes. I agree this can be closed.
