### ISSUE TITLE
Using asymmetric PSF in HAL

### ISSUE THREAD

**Issue by zhoouhaoo** [threeML/hawc_hal#59]
## Feature Request

We need to read asymmetric PSF (asymmetric double gaussian function) from detector response file and use it to convolve point and extended sources.

**Comment by hayalaso** [comment]
I'm joining the party late, but I started looking into tools for convolving 2D spaces. I noticed that currently, we have in `psf_convolutor.py` the following imports:

```
from numpy.fft import rfftn, irfftn
#from scipy.signal import fftconvolve
from scipy.fftpack import helper
```

I found out that astropy also has some convolution libraries. I played with some functions from the tutorial in [here](https://docs.astropy.org/en/stable/convolution/index.html). 

It has the options to create the PSF (kernels in astropy lingo), so, if I'm thinking this correctly, we could fit the 2D gaussian PSF in  HAWC simulations, save the widths, and use `Gaussian2DKernel`([here](https://docs.astropy.org/en/stable/api/astropy.convolution.Gaussian2DKernel.html#astropy.convolution.Gaussian2DKernel)). It even has an option if the Gaussian is tilted. Or if we save 2D histograms, there's a `CustomKernel` ([here](https://docs.astropy.org/en/stable/api/astropy.convolution.CustomKernel.html#astropy.convolution.CustomKernel)) to create your own PSFs. 

To convolve there are the `convolve` and `convolve_fft` functions.
