### ISSUE TITLE
Pull request 43 wasn't implemented

### ISSUE THREAD

**Issue by hayalaso** [threeML/hawc_hal#76]
## Feature Request

The pull request #43  wasn't implemented and became stale. As per its description, 

> the branch allows for subsets of data to be properly analyzed which may only contain (for example) 300 days of data taken over 1500 days. This allows the user to set the HAL plugin to compute the flux over the full 1500 days rather than the 300 days of data contained in the map itself.

**Comment by henrikef** [comment]
I just re-opened it.
